version: '3.8'

services:
  db-test:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: test_dz_bus_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Different port to avoid conflict
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

  redis-test:
    image: redis:7
    ports:
      - "6380:6379"  # Different port to avoid conflict

  test:
    build: .
    command: python manage.py test
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.test
      - DB_HOST=db-test
      - DB_NAME=test_dz_bus_tracker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis-test:6379/0
    depends_on:
      - db-test
      - redis-test
    volumes:
      - .:/app

volumes:
  test_postgres_data: