//! Uploads to private object storage: what each purpose accepts and how objects are named.

use std::fmt;

use crate::error::Violation;
use crate::ids::{UploadId, UserId};

const MIB: u64 = 1024 * 1024;

/// Image formats accepted for photos.
const IMAGES: &[&str] = &["image/jpeg", "image/png", "image/webp"];
/// Identity documents may also be scanned to PDF.
const DOCUMENTS: &[&str] = &["image/jpeg", "image/png", "image/webp", "application/pdf"];

/// What an upload will be attached to. Each purpose has its own accepted types, size limit and
/// required permission (see [`crate::authz::Action::RequestUpload`]).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum UploadPurpose {
    Avatar,
    DriverIdCard,
    DriverLicense,
    BusPhoto,
    StopPhoto,
}

impl UploadPurpose {
    pub const ALL: [Self; 5] =
        [Self::Avatar, Self::DriverIdCard, Self::DriverLicense, Self::BusPhoto, Self::StopPhoto];

    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Avatar => "avatar",
            Self::DriverIdCard => "driver_id_card",
            Self::DriverLicense => "driver_license",
            Self::BusPhoto => "bus_photo",
            Self::StopPhoto => "stop_photo",
        }
    }

    pub fn parse(raw: &str) -> Result<Self, Violation> {
        Self::ALL.into_iter().find(|p| p.as_str() == raw).ok_or_else(|| Violation::InvalidChoice {
            allowed: Self::ALL.iter().map(|p| p.as_str().into()).collect(),
        })
    }

    /// Media types accepted for this purpose.
    #[must_use]
    pub const fn allowed_content_types(self) -> &'static [&'static str] {
        match self {
            Self::DriverIdCard | Self::DriverLicense => DOCUMENTS,
            Self::Avatar | Self::BusPhoto | Self::StopPhoto => IMAGES,
        }
    }

    /// Largest accepted object, in bytes.
    #[must_use]
    pub const fn max_size_bytes(self) -> u64 {
        match self {
            Self::Avatar => 2 * MIB,
            Self::DriverIdCard | Self::DriverLicense => 10 * MIB,
            Self::BusPhoto | Self::StopPhoto => 5 * MIB,
        }
    }

    /// Normalizes a declared media type (trimmed, lower-cased) and checks it is accepted.
    pub fn check_content_type(self, raw: &str) -> Result<&'static str, Violation> {
        let normalized = raw.trim().to_ascii_lowercase();
        self.allowed_content_types().iter().copied().find(|t| *t == normalized).ok_or_else(|| {
            Violation::InvalidChoice {
                allowed: self.allowed_content_types().iter().map(|t| (*t).into()).collect(),
            }
        })
    }

    /// Checks a declared size (bytes) against the limit of the purpose.
    pub fn check_size(self, size_bytes: u64) -> Result<u32, Violation> {
        let max = self.max_size_bytes();
        match u32::try_from(size_bytes) {
            Ok(size) if size > 0 && size_bytes <= max => Ok(size),
            _ => Err(Violation::OutOfRange { min: 1, max: i64::try_from(max).unwrap_or(i64::MAX) }),
        }
    }
}

impl fmt::Display for UploadPurpose {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Lifecycle of an upload.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UploadStatus {
    /// Waiting for the client to upload the object and attach it to a resource.
    Pending,
    /// Referenced by a resource; can never be claimed again.
    Attached,
}

impl UploadStatus {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Attached => "attached",
        }
    }

    #[must_use]
    pub fn parse(raw: &str) -> Option<Self> {
        match raw {
            "pending" => Some(Self::Pending),
            "attached" => Some(Self::Attached),
            _ => None,
        }
    }
}

/// The object key of an upload: `<purpose>/<owner_id>/<upload_id>`. Keys are generated by the
/// server only, never derived from client file names, so they cannot collide or traverse.
#[must_use]
pub fn object_key(purpose: UploadPurpose, owner: UserId, id: UploadId) -> String {
    format!("{}/{owner}/{id}", purpose.as_str())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn purposes_round_trip() {
        for purpose in UploadPurpose::ALL {
            assert_eq!(UploadPurpose::parse(purpose.as_str()), Ok(purpose));
        }
        assert!(matches!(UploadPurpose::parse("selfie"), Err(Violation::InvalidChoice { .. })));
    }

    #[test]
    fn content_types_depend_on_the_purpose() {
        assert_eq!(UploadPurpose::Avatar.check_content_type(" Image/PNG "), Ok("image/png"));
        assert!(UploadPurpose::Avatar.check_content_type("application/pdf").is_err());
        assert_eq!(
            UploadPurpose::DriverLicense.check_content_type("application/pdf"),
            Ok("application/pdf")
        );
        assert!(UploadPurpose::StopPhoto.check_content_type("image/svg+xml").is_err());
    }

    #[test]
    fn sizes_are_bounded_per_purpose() {
        let avatar = UploadPurpose::Avatar;
        assert_eq!(avatar.check_size(1), Ok(1));
        assert_eq!(avatar.check_size(2 * MIB), Ok(2 * 1024 * 1024));
        let too_big = Err(Violation::OutOfRange { min: 1, max: 2 * 1024 * 1024 });
        assert_eq!(avatar.check_size(2 * MIB + 1), too_big);
        assert!(avatar.check_size(0).is_err());
        assert!(UploadPurpose::DriverIdCard.check_size(10 * MIB).is_ok());
        assert!(UploadPurpose::BusPhoto.check_size(5 * MIB + 1).is_err());
        assert!(UploadPurpose::StopPhoto.check_size(u64::MAX).is_err());
    }

    #[test]
    fn object_keys_are_server_generated() {
        let owner = UserId::generate();
        let id = UploadId::generate();
        let key = object_key(UploadPurpose::BusPhoto, owner, id);
        assert_eq!(key, format!("bus_photo/{owner}/{id}"));
    }
}
