-- Uploads: objects that clients put directly into private object storage through presigned
-- URLs, before a resource (avatar, driver documents, bus or stop photo) refers to them.
--
-- Lifecycle: `POST /api/v1/uploads` inserts a `pending` row and returns a presigned PUT; an
-- "attach" endpoint claims it (owner, purpose, expiry and the stored object are checked) and
-- marks it `attached` in the same transaction that stores the object key on the resource.
-- Pending rows that expired are purged hourly together with their objects.

CREATE TABLE uploads (
    id           uuid        PRIMARY KEY,
    -- Uploads belong to a human account; they disappear with it (the objects of attached
    -- uploads are referenced by the account's resources, which are deleted with it as well).
    owner_id     uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    purpose      text        NOT NULL,
    -- Generated by the server only: `<purpose>/<upload_id>`, never from a client
    -- file name. Unique so that two rows can never claim the same object.
    object_key   text        NOT NULL,
    -- The declared type and size; both are signed into the presigned PUT and checked against
    -- the stored object when the upload is claimed.
    content_type text        NOT NULL,
    size_bytes   integer     NOT NULL,
    status       text        NOT NULL DEFAULT 'pending',
    created_at   timestamptz NOT NULL,
    expires_at   timestamptz NOT NULL,
    attached_at  timestamptz,
    CONSTRAINT uploads_object_key_key UNIQUE (object_key),
    CONSTRAINT uploads_purpose_check CHECK (
        purpose IN ('avatar', 'driver_id_card', 'driver_license', 'bus_photo', 'stop_photo')
    ),
    CONSTRAINT uploads_object_key_length CHECK (char_length(object_key) BETWEEN 1 AND 512),
    CONSTRAINT uploads_content_type_length CHECK (char_length(content_type) BETWEEN 1 AND 100),
    CONSTRAINT uploads_size_positive CHECK (size_bytes > 0),
    CONSTRAINT uploads_status_check CHECK (status IN ('pending', 'attached')),
    -- An upload is attached exactly when it records when it was attached.
    CONSTRAINT uploads_attached_consistent CHECK ((status = 'attached') = (attached_at IS NOT NULL)),
    CONSTRAINT uploads_lifetime CHECK (expires_at > created_at)
);

-- Hourly purge of expired pending uploads:
--   SELECT id, object_key FROM uploads
--   WHERE status = 'pending' AND expires_at < $1 ORDER BY expires_at LIMIT 500
-- → Index Scan using uploads_pending_expires_idx (attached rows, the vast majority over time,
--   are not in the index).
CREATE INDEX uploads_pending_expires_idx ON uploads (expires_at) WHERE status = 'pending';
-- `ON DELETE CASCADE` from `users` finds the rows of the deleted account by owner.
CREATE INDEX uploads_owner_idx ON uploads (owner_id);
