# Generated by Django 5.2.12 on 2026-03-12 01:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lines", "0003_servicedisruption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedisruption",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="servicedisruption",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="servicedisruption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
