# Generated by Django 5.1.8 on 2025-04-16 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buses", "0002_initial"),
        ("lines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ETANotification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "notification_threshold",
                    models.PositiveIntegerField(
                        default=5, verbose_name="notification threshold (minutes)"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="sent")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("push", "Push"), ("sms", "SMS"), ("email", "Email")],
                        default="push",
                        max_length=20,
                        verbose_name="notification type",
                    ),
                ),
                (
                    "notification_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="notification ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "ETA notification",
                "verbose_name_plural": "ETA notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StopArrival",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("arrival_time", models.DateTimeField(verbose_name="arrival time")),
                (
                    "departure_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="departure time"
                    ),
                ),
                (
                    "scheduled_arrival_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="scheduled arrival time"
                    ),
                ),
                (
                    "delay_minutes",
                    models.IntegerField(default=0, verbose_name="delay minutes"),
                ),
            ],
            options={
                "verbose_name": "stop arrival",
                "verbose_name_plural": "stop arrivals",
                "ordering": ["-arrival_time"],
            },
        ),
        migrations.CreateModel(
            name="ETA",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "estimated_arrival_time",
                    models.DateTimeField(verbose_name="estimated arrival time"),
                ),
                (
                    "actual_arrival_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="actual arrival time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("approaching", "Approaching"),
                            ("arrived", "Arrived"),
                            ("delayed", "Delayed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "delay_minutes",
                    models.IntegerField(default=0, verbose_name="delay minutes"),
                ),
                (
                    "accuracy",
                    models.IntegerField(default=60, verbose_name="accuracy (seconds)"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etas",
                        to="buses.bus",
                        verbose_name="bus",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etas",
                        to="lines.line",
                        verbose_name="line",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etas",
                        to="lines.stop",
                        verbose_name="stop",
                    ),
                ),
            ],
            options={
                "verbose_name": "ETA",
                "verbose_name_plural": "ETAs",
                "ordering": ["estimated_arrival_time"],
            },
        ),
    ]
