# Generated by Django 5.1.8 on 2025-04-16 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buses", "0002_initial"),
        ("eta", "0001_initial"),
        ("lines", "0001_initial"),
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eta",
            name="tracking_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etas",
                to="tracking.trackingsession",
                verbose_name="tracking session",
            ),
        ),
        migrations.AddField(
            model_name="etanotification",
            name="eta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="eta.eta",
                verbose_name="ETA",
            ),
        ),
        migrations.AddField(
            model_name="etanotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eta_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="stoparrival",
            name="bus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stop_arrivals",
                to="buses.bus",
                verbose_name="bus",
            ),
        ),
        migrations.AddField(
            model_name="stoparrival",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stop_arrivals",
                to="lines.line",
                verbose_name="line",
            ),
        ),
        migrations.AddField(
            model_name="stoparrival",
            name="stop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrivals",
                to="lines.stop",
                verbose_name="stop",
            ),
        ),
        migrations.AddField(
            model_name="stoparrival",
            name="tracking_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stop_arrivals",
                to="tracking.trackingsession",
                verbose_name="tracking session",
            ),
        ),
        migrations.AddIndex(
            model_name="eta",
            index=models.Index(
                fields=["line", "stop"], name="eta_eta_line_id_661ee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eta",
            index=models.Index(fields=["bus"], name="eta_eta_bus_id_7219cc_idx"),
        ),
        migrations.AddIndex(
            model_name="eta",
            index=models.Index(
                fields=["tracking_session"], name="eta_eta_trackin_b41e68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eta",
            index=models.Index(
                fields=["estimated_arrival_time"], name="eta_eta_estimat_0d14c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eta",
            index=models.Index(fields=["status"], name="eta_eta_status_0587f3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="etanotification",
            unique_together={("eta", "user", "notification_type")},
        ),
        migrations.AddIndex(
            model_name="stoparrival",
            index=models.Index(
                fields=["tracking_session"], name="eta_stoparr_trackin_ed5390_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stoparrival",
            index=models.Index(
                fields=["line", "stop"], name="eta_stoparr_line_id_8cf946_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stoparrival",
            index=models.Index(fields=["bus"], name="eta_stoparr_bus_id_ced6a7_idx"),
        ),
        migrations.AddIndex(
            model_name="stoparrival",
            index=models.Index(
                fields=["arrival_time"], name="eta_stoparr_arrival_9a49b0_idx"
            ),
        ),
    ]
