# Generated by Django 5.2.1 on 2025-05-18 04:48

import apps.core.utils.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, validators=[apps.core.utils.validators.validate_phone_number], verbose_name='phone number')),
                ('id_card_number', models.CharField(max_length=20, unique=True, validators=[apps.core.utils.validators.validate_id_card_number], verbose_name='ID card number')),
                ('id_card_photo', models.ImageField(upload_to='drivers/id_cards/', verbose_name='ID card photo')),
                ('driver_license_number', models.CharField(max_length=20, unique=True, verbose_name='driver license number')),
                ('driver_license_photo', models.ImageField(upload_to='drivers/licenses/', verbose_name='driver license photo')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='status')),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='status changed at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0, verbose_name='years of experience')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('total_ratings', models.PositiveIntegerField(default=0, verbose_name='total ratings')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'driver',
                'verbose_name_plural': 'drivers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverRating',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('rating_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='rating date')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='drivers.driver', verbose_name='driver')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_ratings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'driver rating',
                'verbose_name_plural': 'driver ratings',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('driver', 'user', 'rating_date'), name='unique_driver_user_date_rating')],
            },
        ),
    ]
