# Generated by Django 5.1.8 on 2025-04-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverrating",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_ratings",
                to="tracking.trackingsession",
                verbose_name="trip",
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(fields=["user"], name="drivers_dri_user_id_bd76ee_idx"),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["id_number"], name="drivers_dri_id_numb_6ddb2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["license_number"], name="drivers_dri_license_ce5f7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["is_verified"], name="drivers_dri_is_veri_98c4c3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="driverrating",
            unique_together={("driver", "passenger", "trip")},
        ),
    ]
