# Generated by Django 5.2.1 on 2025-07-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='average_speed',
            field=models.FloatField(default=30.0, help_text='Average speed in km/h for ETA calculations', verbose_name='average speed'),
        ),
    ]
