# Generated by Django 5.2.1 on 2025-07-24 22:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('polyline', models.TextField(help_text='Encoded polyline for the route segment')),
                ('distance', models.FloatField(help_text='Distance in kilometers')),
                ('duration', models.IntegerField(help_text='Estimated duration in minutes')),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments_from', to='lines.stop')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments_to', to='lines.stop')),
            ],
            options={
                'db_table': 'tracking_route_segments',
                'indexes': [models.Index(fields=['from_stop', 'to_stop'], name='tracking_ro_from_st_96daf8_idx')],
                'unique_together': {('from_stop', 'to_stop')},
            },
        ),
    ]
