# Generated by Django 5.2.1 on 2025-07-27 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_bus_average_speed'),
        ('lines', '0001_initial'),
        ('tracking', '0002_routesegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reports', models.PositiveIntegerField(default=0, verbose_name='total reports')),
                ('correct_reports', models.PositiveIntegerField(default=0, verbose_name='correct reports')),
                ('reputation_level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20, verbose_name='reputation level')),
                ('trust_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text="Weight given to user's reports (0.50-2.00)", max_digits=3, verbose_name='trust multiplier')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_score', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'reputation score',
                'verbose_name_plural': 'reputation scores',
            },
        ),
        migrations.CreateModel(
            name='VirtualCurrency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='Current virtual currency balance', verbose_name='balance')),
                ('lifetime_earned', models.IntegerField(default=0, verbose_name='lifetime earned')),
                ('lifetime_spent', models.IntegerField(default=0, verbose_name='lifetime spent')),
                ('last_transaction', models.DateTimeField(blank=True, null=True, verbose_name='last transaction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_currency', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'virtual currency',
                'verbose_name_plural': 'virtual currencies',
            },
        ),
        migrations.CreateModel(
            name='WaitingCountReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_count', models.PositiveSmallIntegerField(help_text='Number of people waiting as reported by user', verbose_name='reported count')),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='confidence level')),
                ('confidence_score', models.DecimalField(decimal_places=3, default=0.5, help_text='System-calculated accuracy score (0-1)', max_digits=5, verbose_name='confidence score')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('correct', 'Correct'), ('incorrect', 'Incorrect'), ('partially_correct', 'Partially Correct')], default='pending', max_length=20, verbose_name='verification status')),
                ('actual_count', models.PositiveSmallIntegerField(blank=True, help_text='Actual count as verified by driver', null=True, verbose_name='actual count')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('location_verified', models.BooleanField(default=False, help_text='GPS confirms reporter is at stop', verbose_name='location verified')),
                ('reporter_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='reporter latitude')),
                ('reporter_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='reporter longitude')),
                ('bus', models.ForeignKey(blank=True, help_text="Specific bus they're waiting for", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_count_reports', to='buses.bus', verbose_name='bus')),
                ('line', models.ForeignKey(blank=True, help_text="Line they're waiting for", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_count_reports', to='lines.line', verbose_name='line')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_count_reports', to='lines.stop', verbose_name='stop')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
            ],
            options={
                'verbose_name': 'waiting count report',
                'verbose_name_plural': 'waiting count reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for earning, negative for spending/penalty', verbose_name='amount')),
                ('transaction_type', models.CharField(choices=[('accurate_report', 'Accurate Report'), ('false_report', 'False Report'), ('waiting_bonus', 'Waiting Bonus'), ('consistency_bonus', 'Consistency Bonus'), ('early_adopter', 'Early Adopter Bonus'), ('driver_verification', 'Driver Verification Bonus'), ('reward_purchase', 'Reward Purchase'), ('penalty', 'Penalty'), ('admin_adjustment', 'Admin Adjustment')], max_length=30, verbose_name='transaction type')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('balance_after', models.IntegerField(help_text="User's balance after this transaction", verbose_name='balance after')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction data', verbose_name='metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_transactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_transactions', to='tracking.waitingcountreport', verbose_name='related report')),
            ],
            options={
                'verbose_name': 'currency transaction',
                'verbose_name_plural': 'currency transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusWaitingList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('estimated_arrival', models.DateTimeField(blank=True, help_text='Bus ETA when user joined the waiting list', null=True, verbose_name='estimated arrival')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the user is still waiting', verbose_name='is active')),
                ('notified_on_arrival', models.BooleanField(default=False, verbose_name='notified on arrival')),
                ('left_at', models.DateTimeField(blank=True, help_text='When user left the waiting list', null=True, verbose_name='left at')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_passengers', to='buses.bus', verbose_name='bus')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_waiting_lists', to='lines.stop', verbose_name='stop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_lists', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'bus waiting list',
                'verbose_name_plural': 'bus waiting lists',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['bus', 'stop', 'is_active'], name='tracking_bu_bus_id_27067e_idx'), models.Index(fields=['user', 'is_active'], name='tracking_bu_user_id_c57434_idx')],
                'unique_together': {('bus', 'stop', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='waitingcountreport',
            index=models.Index(fields=['stop', 'bus', '-created_at'], name='tracking_wa_stop_id_efd264_idx'),
        ),
        migrations.AddIndex(
            model_name='waitingcountreport',
            index=models.Index(fields=['reporter', '-created_at'], name='tracking_wa_reporte_26cdf3_idx'),
        ),
        migrations.AddIndex(
            model_name='waitingcountreport',
            index=models.Index(fields=['verification_status'], name='tracking_wa_verific_851e28_idx'),
        ),
        migrations.AddIndex(
            model_name='currencytransaction',
            index=models.Index(fields=['user', '-created_at'], name='tracking_cu_user_id_0df35e_idx'),
        ),
        migrations.AddIndex(
            model_name='currencytransaction',
            index=models.Index(fields=['transaction_type'], name='tracking_cu_transac_79a439_idx'),
        ),
    ]
