# Generated by Django 5.2.1 on 2025-07-27 19:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('tracking', '0003_reputationscore_virtualcurrency_waitingcountreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='feature name')),
                ('feature_type', models.CharField(choices=[('route_analytics', 'Advanced Route Analytics'), ('performance_insights', 'Detailed Performance Insights'), ('passenger_feedback', 'Real-time Passenger Feedback'), ('priority_support', 'Priority Customer Support'), ('custom_dashboard', 'Customizable Dashboard'), ('fuel_optimization', 'Fuel Optimization Tips'), ('earnings_tracker', 'Advanced Earnings Tracker'), ('schedule_optimizer', 'Smart Schedule Optimizer'), ('maintenance_alerts', 'Predictive Maintenance Alerts'), ('competition_stats', 'Driver Competition Statistics')], max_length=30, verbose_name='feature type')),
                ('description', models.TextField(verbose_name='description')),
                ('cost_coins', models.PositiveIntegerField(help_text='Cost to unlock this feature', verbose_name='cost in coins')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='How long the feature stays active', verbose_name='duration in days')),
                ('target_users', models.CharField(choices=[('passengers', 'Passengers'), ('drivers', 'Drivers'), ('all', 'All Users')], default='all', max_length=20, verbose_name='target users')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('required_level', models.CharField(blank=True, choices=[('rookie', 'Rookie'), ('experienced', 'Experienced'), ('expert', 'Expert'), ('master', 'Master')], help_text='Minimum performance level required (drivers only)', max_length=20, null=True, verbose_name='required performance level')),
            ],
            options={
                'verbose_name': 'premium feature',
                'verbose_name_plural': 'premium features',
            },
        ),
        migrations.AlterField(
            model_name='currencytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('accurate_report', 'Accurate Report'), ('false_report', 'False Report'), ('waiting_bonus', 'Waiting Bonus'), ('consistency_bonus', 'Consistency Bonus'), ('early_adopter', 'Early Adopter Bonus'), ('driver_verification', 'Driver Verification Bonus'), ('reward_purchase', 'Reward Purchase'), ('penalty', 'Penalty'), ('admin_adjustment', 'Admin Adjustment'), ('on_time_performance', 'On-Time Performance Bonus'), ('excellent_service', 'Excellent Service Rating'), ('safe_driving', 'Safe Driving Bonus'), ('fuel_efficiency', 'Fuel Efficiency Bonus'), ('passenger_satisfaction', 'High Passenger Satisfaction'), ('route_completion', 'Route Completion Bonus'), ('verification_accuracy', 'Report Verification Accuracy'), ('weekly_achievement', 'Weekly Achievement'), ('monthly_achievement', 'Monthly Achievement'), ('premium_purchase', 'Premium Feature Purchase'), ('achievement_unlock', 'Achievement Unlocked'), ('streak_bonus', 'Performance Streak Bonus')], max_length=30, verbose_name='transaction type'),
        ),
        migrations.CreateModel(
            name='DriverPerformanceScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trips', models.PositiveIntegerField(default=0, verbose_name='total trips')),
                ('on_time_trips', models.PositiveIntegerField(default=0, verbose_name='on-time trips')),
                ('performance_level', models.CharField(choices=[('rookie', 'Rookie'), ('experienced', 'Experienced'), ('expert', 'Expert'), ('master', 'Master')], default='rookie', max_length=20, verbose_name='performance level')),
                ('safety_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='safety score')),
                ('passenger_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='passenger rating')),
                ('fuel_efficiency_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='fuel efficiency score')),
                ('report_verification_accuracy', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='report verification accuracy')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Days of excellent performance', verbose_name='current performance streak')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='best performance streak')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_score', to='drivers.driver', verbose_name='driver')),
            ],
            options={
                'verbose_name': 'driver performance score',
                'verbose_name_plural': 'driver performance scores',
            },
        ),
        migrations.CreateModel(
            name='UserPremiumFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='purchased at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('coins_spent', models.PositiveIntegerField(verbose_name='coins spent')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchases', to='tracking.premiumfeature', verbose_name='feature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_features', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user premium feature',
                'verbose_name_plural': 'user premium features',
                'indexes': [models.Index(fields=['user', 'is_active'], name='tracking_us_user_id_0944de_idx'), models.Index(fields=['feature', 'is_active'], name='tracking_us_feature_b394c4_idx')],
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
