# Generated by Django 5.2.12 on 2026-03-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_premiumfeature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premiumfeature",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("route_analytics", "Advanced Route Analytics"),
                    ("performance_insights", "Detailed Performance Insights"),
                    ("passenger_feedback", "Real-time Passenger Feedback"),
                    ("priority_support", "Priority Customer Support"),
                    ("custom_dashboard", "Customizable Dashboard"),
                ],
                max_length=30,
                verbose_name="feature type",
            ),
        ),
    ]
