# Generated by Django 5.2.12 on 2026-03-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0007_remove_orphaned_premium_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reputationscore",
            name="correct_reports",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Supports 0.5 credit for partially_correct verifications",
                max_digits=10,
                verbose_name="correct reports",
            ),
        ),
    ]
