# Generated by Django 5.1.8 on 2025-04-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedules", "0001_initial"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtrip",
            name="tracking_session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_trip",
                to="tracking.trackingsession",
                verbose_name="tracking session",
            ),
        ),
        migrations.AddField(
            model_name="scheduleexception",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exceptions",
                to="schedules.schedule",
                verbose_name="schedule",
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["line"], name="schedules_s_line_id_490d95_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["bus"], name="schedules_s_bus_id_03b2a8_idx"),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["driver"], name="schedules_s_driver__d274cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["start_time"], name="schedules_s_start_t_9ce5a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtrip",
            index=models.Index(
                fields=["schedule"], name="schedules_s_schedul_6bb21d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtrip",
            index=models.Index(fields=["date"], name="schedules_s_date_ac363e_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledtrip",
            index=models.Index(fields=["status"], name="schedules_s_status_ab6580_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledtrip",
            index=models.Index(
                fields=["start_time"], name="schedules_s_start_t_ac79e8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scheduleexception",
            unique_together={("schedule", "date")},
        ),
    ]
