# Generated by Django 5.1.8 on 2025-04-16 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("bus_approaching", "Bus Approaching"),
                            ("delay", "Delay"),
                            ("cancellation", "Cancellation"),
                            ("verification", "Verification"),
                            ("news", "News"),
                        ],
                        default="system",
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="data"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "sent_via_push",
                    models.BooleanField(default=False, verbose_name="sent via push"),
                ),
                (
                    "sent_via_email",
                    models.BooleanField(default=False, verbose_name="sent via email"),
                ),
                (
                    "sent_via_sms",
                    models.BooleanField(default=False, verbose_name="sent via SMS"),
                ),
                (
                    "is_action_required",
                    models.BooleanField(default=False, verbose_name="action required"),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="action URL"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiration date"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("push", "Push"), ("email", "Email"), ("sms", "SMS")],
                        max_length=50,
                        verbose_name="method",
                    ),
                ),
                ("success", models.BooleanField(default=False, verbose_name="success")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="provider response"
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="notifications.notification",
                        verbose_name="notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification log",
                "verbose_name_plural": "notification logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("bus_approaching", "Bus Approaching"),
                            ("delay", "Delay"),
                            ("cancellation", "Cancellation"),
                            ("verification", "Verification"),
                            ("news", "News"),
                        ],
                        max_length=50,
                        verbose_name="notification type",
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(default=True, verbose_name="push enabled"),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="email enabled"),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(default=False, verbose_name="SMS enabled"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
                "ordering": ["user", "notification_type"],
            },
        ),
        migrations.CreateModel(
            name="PushToken",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Deleted"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                ("token", models.TextField(verbose_name="token")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        max_length=50,
                        verbose_name="device type",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="device name"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="last used"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "push token",
                "verbose_name_plural": "push tokens",
                "ordering": ["-last_used"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user"], name="notificatio_user_id_c291d5_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["type"], name="notificatio_type_ea918f_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["is_read"], name="notificatio_is_read_9edb86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_46ad24_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together={("user", "notification_type")},
        ),
        migrations.AlterUniqueTogether(
            name="pushtoken",
            unique_together={("user", "token")},
        ),
    ]
