# Generated by Django 5.2.1 on 2025-05-18 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='token')),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20, verbose_name='device type')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='last used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'device token',
                'verbose_name_plural': 'device tokens',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'token')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('driver_approved', 'Driver Approved'), ('driver_rejected', 'Driver Rejected'), ('bus_arriving', 'Bus Arriving'), ('bus_delayed', 'Bus Delayed'), ('bus_cancelled', 'Bus Cancelled'), ('system', 'System')], max_length=50, verbose_name='notification type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('channel', models.CharField(choices=[('push', 'Push'), ('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In App')], default='in_app', max_length=20, verbose_name='channel')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification', verbose_name='data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
